name: gregsgrid
favicon: null
layout_spectrum: 0.40837511979043484
typography_spectrum: 0.995167221641168
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9005873075220734
  lightness: 0.618143423460424
  saturation: 0.1955753923393786
  rhythmicContrast: 0.3314060363918543
purpose: []
